name: PR Template Verification

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  verify_template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Verify PR template
        run: |
          template_content=$(cat ${{ github.event.pull_request.files[0].filename }})
          if [[ $template_content == *"## Description"* ]] &&
             [[ $template_content == *"## Type of change"* ]] &&
             [[ $template_content == *"## How Has This Been Tested?"* ]] &&
             [[ $template_content == *"## Checklist:"* ]] &&
             ( [[ $template_content == *"- [x]"* ]] ||
               [[ $template_content == *"- [ ]"* ]] )
          then
            echo "PR template verified successfully"
          else
            echo "PR template verification failed"
            exit 1
          fi
