name: PR Template Checker

on:
  pull_request:
    types: [opened, edited]

jobs:
  verify-pr-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Verify PR template
        run: |
          PR_BODY=$(cat $GITHUB_EVENT_PATH | jq -r '.pull_request.body')
          if [[ ! $PR_BODY =~ "## Description" || ! $PR_BODY =~ "## Type of change" || ! $PR_BODY =~ "## How Has This Been Tested?" || ! $PR_BODY =~ "## Checklist:" || ! $PR_BODY =~ "Fixes #[0-9]+" ]]; then
            echo "One or more sections of the PR template are missing!"
            exit 1
          fi

          # Check if description is present
          if [[ $(echo "$PR_BODY" | grep -c "## Description") -ne 1 ]]; then
            echo "Description section is missing or duplicated!"
            exit 1
          fi

          # Check if type of change is present
          if [[ $(echo "$PR_BODY" | grep -c "## Type of change") -ne 1 ]]; then
            echo "Type of change section is missing or duplicated!"
            exit 1
          fi

          # Check if How Has This Been Tested? section is present
          if [[ $(echo "$PR_BODY" | grep -c "## How Has This Been Tested?") -ne 1 ]]; then
            echo "How Has This Been Tested? section is missing or duplicated!"
            exit 1
          fi

          # Check if Checklist section is present
          if [[ $(echo "$PR_BODY" | grep -c "## Checklist:") -ne 1 ]]; then
            echo "Checklist section is missing or duplicated!"
            exit 1
          fi

          # Check if Fixes #(issue) is present
          if [[ $(echo "$PR_BODY" | grep -c "Fixes #[0-9]+") -ne 1 ]]; then
            echo "Fixes #(issue) is missing or duplicated!"
            exit 1
          fi
