name: PR Template Checker

on:
  pull_request:
    types: [opened, edited]

jobs:
  verify-pr-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Verify PR template
        run: |
          PR_BODY=$(cat $GITHUB_EVENT_PATH | jq -r '.pull_request.body')
          if [[ ! $PR_BODY =~ "## Description" || ! $PR_BODY =~ "## Type of change" || ! $PR_BODY =~ "## How Has This Been Tested?" || ! $PR_BODY =~ "## Checklist:" ]]; then
            echo "PR template is not followed!"
            exit 1
          fi
