name: PR Rotation

on:
  pull_request_target:
    types: [opened]

jobs:
  rotate_reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Current Reviewer Index
        id: get_index
        run: |
          index_file=.reviewer_index
          if [ ! -f "$index_file" ]; then
            echo "0" > "$index_file"
          fi
          current_index=$(cat "$index_file")
          echo "::set-output name=index::$current_index"
      - name: Rotate Reviewers
        id: rotate
        run: |
          reviewers=("suryagowdaa" "arko-maersk")
          index=${{ steps.get_index.outputs.index }}
          current_reviewer=${reviewers[$index]}
          next_index=$((($index + 1) % ${#reviewers[@]}))
          echo "::set-output name=reviewer::$current_reviewer"
          echo "$next_index" > .reviewer_index
      - name: Assign Reviewer
        uses: thenpm/gh-action-assign-reviewer@v2
        with:
          reviewers: ${{ steps.rotate.outputs.reviewer }}
