name: Assign PR Reviewer

on:
  pull_request_target:
    types: [opened]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Current Reviewer
        id: get_reviewer
        run: |
          reviewer_file=.current_reviewer
          if [ -f "$reviewer_file" ]; then
            current_reviewer=$(cat "$reviewer_file")
          else
            current_reviewer=""
          fi
          echo "::set-output name=reviewer::$current_reviewer"

      - name: Rotate Reviewers
        id: rotate
        run: |
          reviewers=("suryagowdaa" "arko-maersk" "prachimat")
          current_reviewer=${{ steps.get_reviewer.outputs.reviewer }}
          if [ -z "$current_reviewer" ]; then
            current_index=0
          else
            current_index=$(printf "%s\n" "${reviewers[@]}" | grep -nx "$current_reviewer" | cut -d: -f1)
            current_index=$((current_index - 1))
          fi
          next_index=$((($current_index + 1) % ${#reviewers[@]}))
          next_reviewer=${reviewers[$next_index]}
          echo "$next_reviewer" > .current_reviewer
          echo "::set-output name=reviewer::$next_reviewer"

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Assign Reviewer
        run: |
          PULL_REQUEST_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          REVIEWER=${{ steps.rotate.outputs.reviewer }}
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PULL_REQUEST_NUMBER/requested_reviewers \
            -d "{\"reviewers\":[\"$REVIEWER\"]}"
