name: PR Rotation

on:
  pull_request_target:
    types: [opened]

jobs:
  rotate_reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Rotate Reviewers
        id: rotate
        run: |
          reviewers=("suryagowdaa" "arko-maersk") 
          pr_number=${{ github.event.pull_request.number }}
          current_reviewer_index=$((pr_number % ${#reviewers[@]}))
          current_reviewer=${reviewers[$current_reviewer_index]}
          echo "::set-output name=reviewer::$current_reviewer"

      - name: Request Reviewer
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pullRequest } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const reviewers = [process.env.reviewer];
            await github.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pullRequest.number,
              reviewers: reviewers,
            });
        env:
          reviewer: ${{ steps.rotate.outputs.reviewer }}
          github-token: ${{ secrets.GITHUB_TOKEN }} 
