name: Pull Request Rotation

on:
  pull_request:
    types: [opened]

jobs:
  rotate_reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: load_reviewers
        name: Load Reviewer List
        run: |
          reviewers_file=".github/workflows/reviewers.txt"
          if [ ! -f "$reviewers_file" ]; then
            echo "Please create a file named '$reviewers_file' containing reviewers (one per line)."
            exit 1
          fi
          reviewers=$(cat "$reviewers_file")

      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            
            const reviewers = core.getInput('reviewers').split(',');  # Assuming reviewers are provided as input
            const currentReviewerIndex = parseInt(core.getState('currentReviewerIndex') || 0);
            const nextReviewerIndex = (currentReviewerIndex + 1) % reviewers.length;
            const nextReviewer = reviewers[nextReviewerIndex];

            const octokit = new github.Octokit({ auth: core.secrets.GITHUB_TOKEN });
            const { owner, repo } = context.repo;
            const pullNumber = context.issue.number;

            try {
              await octokit.issues.addAssignees({
                owner,
                repo,
                issue_number: pullNumber,
                assignees: [nextReviewer]
              });
              core.setState('currentReviewerIndex', nextReviewerIndex.toString());
              console.log(`Pull request #${pullNumber} assigned to @${nextReviewer}`);
            } catch (error) {
              core.setFailed(`Error assigning reviewer: ${error.message}`);
            }
