name: Assign PR Reviewer

on:
  pull_request_target:
    types: [opened]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Current Reviewer Index
        id: get_index
        run: |
          index_file=.reviewer_index
          if [ ! -f "$index_file" ]; then
            echo "current_index=0" >> $GITHUB_ENV
          else
            current_index=$(cat "$index_file")
            echo "current_index=$current_index" >> $GITHUB_ENV
          fi

      - name: Rotate Reviewers
        id: rotate
        run: |
          reviewers=("suryagowdaa" "arko-maersk" "prachimat")
          index=${{ env.current_index }}
          AUTHOR=$(jq --raw-output .pull_request.user.login "$GITHUB_ENV_PATH")

          next_index=$((($index + 1) % ${#reviewers[@]}))
          current_reviewer=${reviewers[$index]}

          while [ "$current_reviewer" == "$AUTHOR" ]; do
            index=$next_index
            next_index=$((($index + 1) % ${#reviewers[@]}))
            current_reviewer=${reviewers[$index]}
          done

          echo "reviewer=$current_reviewer" >> $GITHUB_ENV
          echo "$next_index" > .reviewer_index

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Assign Reviewer
        run: |
          PULL_REQUEST_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          REVIEWER=${{ env.reviewer }}
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PULL_REQUEST_NUMBER/requested_reviewers \
            -d "{\"reviewers\":[\"$REVIEWER\"]}"
