name: PR Rotation

on:
  pull_request_target:
    types: [opened]

jobs:
  rotate_reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Rotate Reviewers
        id: rotate
        run: |
          reviewers=("your-username" "other-guy") # Replace with actual GitHub usernames
          pr_number=${{ github.event.pull_request.number }}
          current_reviewer_index=$(($pr_number % ${#reviewers[@]}))
          current_reviewer=${reviewers[$current_reviewer_index]}
          echo "reviewer=$current_reviewer" >> $GITHUB_ENV
          echo "::set-output name=reviewer::$current_reviewer"

      - name: Request Reviewer
        uses: actions/github-script@v6
        with:
          script: |
            github.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              reviewers: [process.env.reviewer]
            })
        env:
          reviewer: ${{ steps.rotate.outputs.reviewer }}
